name: Earthdata2025
channels:
- conda-forge
dependencies:
- pip
- numpy
- python = 3.12
- netCDF4
- matplotlib
- jupyterlab
- cartopy
- xarray
- earthaccess
- tqdm
- dask
- pandas
- scipy
- pydap
- xoak
- pip:
  - jupyter-contrib-nbextensions
  - ipywidgets 
  - widgetsnbextension


