name: Earthdata2026
channels:
- conda-forge
dependencies:
- pip
- numpy
- python = 3.12
- netCDF4
- matplotlib
- jupyterlab
- cartopy
- earthaccess
- tqdm
- dask
- pandas
- scipy
- xoak
- pyresample
- xarray = 2026.1
- pip:
  - jupyter-contrib-nbextensions
  - ipywidgets 
  - widgetsnbextension
  - git+https://github.com/pydap/pydap.git



