name: Earthdata2026
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - libsqlite
  - numpy
  - netCDF4
  - matplotlib
  - jupyterlab
  - jupyter_server
  - jupyterhub-singleuser
  - cartopy
  - earthaccess
  - ipywidgets
  - tqdm
  - dask
  - pandas
  - scipy
  - xoak
  - pyresample
  - xarray=2026.1
  - pip:
      - git+https://github.com/pydap/pydap.git