name: Test notebooks
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    # Run every monday at 7am EST
    - cron: '0 12 * * 1'

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: binder/environment.yml
          environment-name: Earthdata2026
          create-args: >-
            conda
          cache-environment: true

      - name: Install ci dependencies
        run: |
          which python
          python --version
          pip install jupyter nbconvert

      - name: Create netrc file 
        run: |
          cat <<EOF > $HOME/.netrc
          machine urs.earthdata.nasa.gov
            login ${{ secrets.EDL_USERNAME }}
            password ${{ secrets.EDL_PASSWORD }}
          EOF
          chmod 600 $HOME/.netrc

      - name: Test each notebook sequentially
        run: |
          for file in ./binder/*; do
              if [[ "$file" == *.ipynb ]]; then
                  echo "Running notebook `$file`..."
                  jupyter nbconvert --to notebook --execute binder/$file --output executed_notebook.ipynb
                  if [ $? -eq 0 ]; then
                      echo "...$file succeeded!"
                  else
                      echo "...$file failed"
                      exit 1
                  fi
              fi
          done
