name: Test notebooks
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: binder/environment.yml
          environment-name: Earthdata2026
          create-args: >-
            conda
          cache-environment: true

      - name: Install job dependencies
        run: |
          which python
          python --version
          pip install jupyter nbconvert
          touch .netrc  # TODO-FIX: THIS OBVIOUSLY WILL NOT WORK! :D

      - name: Execute CMR notebook (no EDL required)
        run: |
          jupyter nbconvert --to notebook --execute binder/CMR_queries.ipynb --output executed_notebook.ipynb

      - name: Execute CMR notebook (EDL required)
        run: |
          jupyter nbconvert --to notebook --execute binder/DAYMET.ipynb --output executed_notebook.ipynb
